/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.kappadev.medplus.ui.textTool;

import com.kappadev.medplus.ui.textTool.models.FontComboBoxModel;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.Element;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import javax.swing.text.StyledDocument;
import com.kappadev.medplus.ui.patientLog.PatientLogPanel;

/**
 *
 * @author tburzynski
 */
public class TextTools extends javax.swing.JFrame {
    
    private PatientLogPanel patientLogPanel;
    private DefaultComboBoxModel<FontComboBoxModel> fontComboBoxModel;
    private DefaultComboBoxModel<Integer> fontSizeComboBoxModel;
    /**
     * Creates new form TextTools
     */
    public TextTools() {
        initComponents();
    }
    
    public TextTools(PatientLogPanel patientLogPanel){
        initComponents();
        this.patientLogPanel = patientLogPanel;
        initializeFonts();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fontComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        fontSizeCombo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        closeBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        underlineButton = new javax.swing.JToggleButton();
        italicButton = new javax.swing.JToggleButton();
        boldButton = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Narzędzia edycji tekstu");

        fontComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fontComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Czcionka");

        fontSizeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fontSizeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontSizeComboActionPerformed(evt);
            }
        });

        jLabel4.setText("rozmiar");

        closeBtn.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N
        closeBtn.setText("zamknij");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        underlineButton.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N
        underlineButton.setText("U");
        underlineButton.setPreferredSize(new java.awt.Dimension(22, 26));
        underlineButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                underlineButtonItemStateChanged(evt);
            }
        });

        italicButton.setFont(new java.awt.Font("Cantarell", 2, 15)); // NOI18N
        italicButton.setText("I");
        italicButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                italicButtonItemStateChanged(evt);
            }
        });

        boldButton.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        boldButton.setText("B");
        boldButton.setInheritsPopupMenu(true);
        boldButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boldButtonItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boldButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(italicButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(underlineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(underlineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(italicButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boldButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(fontComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(fontSizeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(115, 115, 115))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 237, Short.MAX_VALUE)
                                        .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fontComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fontSizeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void fontComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontComboBoxActionPerformed
        FontComboBoxModel fcbm = (FontComboBoxModel)fontComboBox.getSelectedItem();
        Font selectedFont = fcbm.getFont();
        setCharacterProperty(StyleConstants.FontFamily, selectedFont.getFontName());
    }//GEN-LAST:event_fontComboBoxActionPerformed

    private void boldButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boldButtonItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            setCharacterProperty(StyleConstants.Bold, Boolean.TRUE);
      } else if(evt.getStateChange()==ItemEvent.DESELECTED){
            removeCharacterProperty(StyleConstants.Bold);
      }
    }//GEN-LAST:event_boldButtonItemStateChanged

    private void italicButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_italicButtonItemStateChanged
       if(evt.getStateChange()==ItemEvent.SELECTED){
            setCharacterProperty(StyleConstants.Italic, Boolean.TRUE);
      } else if(evt.getStateChange()==ItemEvent.DESELECTED){
            removeCharacterProperty(StyleConstants.Italic);
      }
    }//GEN-LAST:event_italicButtonItemStateChanged

    private void underlineButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_underlineButtonItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            setCharacterProperty(StyleConstants.Underline, Boolean.TRUE);
      } else if(evt.getStateChange()==ItemEvent.DESELECTED){
            removeCharacterProperty(StyleConstants.Underline);
      }
    }//GEN-LAST:event_underlineButtonItemStateChanged

    private void fontSizeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontSizeComboActionPerformed
        Integer selectedSize = (Integer)fontSizeCombo.getSelectedItem();
        setCharacterProperty(StyleConstants.FontSize, selectedSize);
    }//GEN-LAST:event_fontSizeComboActionPerformed
    
    private void setCharacterProperty(Object style, Object value){
        StyledDocument sd = patientLogPanel.getDescriptionTxtField().getStyledDocument();
           
        Element element = sd.getCharacterElement(patientLogPanel.getDescriptionTxtField().getCaretPosition());
        AttributeSet attributes = element.getAttributes();
        StyleContext sc = StyleContext.getDefaultStyleContext();
            
        attributes = sc.addAttribute(attributes, style, value);
        
        int length = patientLogPanel.getDescriptionTxtField().getSelectionEnd() - patientLogPanel.getDescriptionTxtField().getSelectionStart();
        if(length<0){
           length = 0;
        }
        sd.setCharacterAttributes(patientLogPanel.getDescriptionTxtField().getSelectionStart(), length, attributes, true);
        patientLogPanel.getDescriptionTxtField().setStyledDocument(sd);
    }
    
    private void removeCharacterProperty(Object style){
        StyledDocument sd = patientLogPanel.getDescriptionTxtField().getStyledDocument();
           
        Element element = sd.getCharacterElement(patientLogPanel.getDescriptionTxtField().getCaretPosition());
        AttributeSet attributes = element.getAttributes();
        StyleContext sc = StyleContext.getDefaultStyleContext();
            
        attributes = sc.removeAttribute(attributes, style);
        int length = patientLogPanel.getDescriptionTxtField().getSelectionEnd() - patientLogPanel.getDescriptionTxtField().getSelectionStart();
        if(length<0){
           length = 0;
        }
        sd.setCharacterAttributes(patientLogPanel.getDescriptionTxtField().getSelectionStart(), length, attributes, true);
        patientLogPanel.getDescriptionTxtField().setStyledDocument(sd);
    }
    
    private void changeFont(Font font){
        patientLogPanel.getDescriptionTxtField().setFont(font);
    }
    
    private void initializeFonts(){
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Font[] fonts = ge.getAllFonts();
        fontComboBoxModel = new DefaultComboBoxModel<>();
        fontSizeComboBoxModel = new DefaultComboBoxModel<>();
        for(Font font : fonts){
            fontComboBoxModel.addElement(new FontComboBoxModel(font));
        }  
        fontComboBox.setModel(fontComboBoxModel);
        fontSizeCombo.setModel(fontSizeComboBoxModel);
        fontSizeCombo.removeAllItems();
        
        for (int i=8; i<72; i=i+2){
            fontSizeCombo.addItem(new Integer(i));
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton boldButton;
    private javax.swing.JButton closeBtn;
    private javax.swing.JComboBox fontComboBox;
    private javax.swing.JComboBox fontSizeCombo;
    private javax.swing.JToggleButton italicButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton underlineButton;
    // End of variables declaration//GEN-END:variables
}
