CREATE USER IF NOT EXISTS ADMIN SALT '9aa4d3837de9ea28' HASH '61d66f02b03aaf16d09ce12a633ea6cf4581a6503fddcaf1497cd32e1a5f93d2' ADMIN;




INSERT INTO STATES(NAME) VALUES ('brak');
INSERT INTO STATES(NAME) VALUES (STRINGDECODE('dolno\u015bl\u0105skie'));
INSERT INTO STATES(NAME) VALUES ('kujawsko-pomorskie');
INSERT INTO STATES(NAME) VALUES ('lubelskie');
INSERT INTO STATES(NAME) VALUES ('lubuskie');
INSERT INTO STATES(NAME) VALUES (STRINGDECODE('\u0142\u00f3dzkie'));
INSERT INTO STATES(NAME) VALUES (STRINGDECODE('ma\u0142opolskie'));
INSERT INTO STATES(NAME) VALUES ('mazowieckie');
INSERT INTO STATES(NAME) VALUES ('opolskie');
INSERT INTO STATES(NAME) VALUES ('podlaskie');
INSERT INTO STATES(NAME) VALUES ('podkarpackie');
INSERT INTO STATES(NAME) VALUES ('pomorskie');
INSERT INTO STATES(NAME) VALUES (STRINGDECODE('\u015bl\u0105skie'));
INSERT INTO STATES(NAME) VALUES (STRINGDECODE('\u015bwi\u0119tokrzyskie'));
INSERT INTO STATES(NAME) VALUES (STRINGDECODE('warmi\u0144sko-mazurskie'));
INSERT INTO STATES(NAME) VALUES ('wielkopolskie');
INSERT INTO STATES(NAME) VALUES ('zachodnio-pomorskie');

INSERT INTO EMAIL_PROVIDER(INCOMING_SERVER_ADDRESS, INCOMING_SERVER_PORT, INCOMING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_ADDRESS, OUTGOING_SERVER_PORT, OUTGOING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_REQUIRES_AUTHENTICATION, PROVIDER_NAME, SERVER_TYPE) VALUES ('imap.gmail.com', 993, true, 'smtp.gmail.com', 465, true, true, 'GMAIL', 'IMAP');
INSERT INTO EMAIL_PROVIDER(INCOMING_SERVER_ADDRESS, INCOMING_SERVER_PORT, INCOMING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_ADDRESS, OUTGOING_SERVER_PORT, OUTGOING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_REQUIRES_AUTHENTICATION, PROVIDER_NAME, SERVER_TYPE) VALUES ('imap.mail.me.com', 993, true, 'smtp.mail.me.com', 465, true, true, 'ICLOUD', 'IMAP');
INSERT INTO EMAIL_PROVIDER(INCOMING_SERVER_ADDRESS, INCOMING_SERVER_PORT, INCOMING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_ADDRESS, OUTGOING_SERVER_PORT, OUTGOING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_REQUIRES_AUTHENTICATION, PROVIDER_NAME, SERVER_TYPE) VALUES ('imap.wp.pl', 993, true, 'smtp.wp.pl', 465, true, true, 'WP_PL', 'IMAP');
INSERT INTO EMAIL_PROVIDER(INCOMING_SERVER_ADDRESS, INCOMING_SERVER_PORT, INCOMING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_ADDRESS, OUTGOING_SERVER_PORT, OUTGOING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_REQUIRES_AUTHENTICATION, PROVIDER_NAME, SERVER_TYPE) VALUES ('imap.poczta.onet.pl', 993, true, 'smtp.poczta.onet.pl', 465, true, true, 'ONET', 'IMAP');
INSERT INTO EMAIL_PROVIDER(INCOMING_SERVER_ADDRESS, INCOMING_SERVER_PORT, INCOMING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_ADDRESS, OUTGOING_SERVER_PORT, OUTGOING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_REQUIRES_AUTHENTICATION, PROVIDER_NAME, SERVER_TYPE) VALUES ('imap-mail.outlook.com', 993, true, 'smtp-mail.outlook.com', 465, true, true, 'OUTLOOK_COM', 'IMAP');
INSERT INTO EMAIL_PROVIDER(INCOMING_SERVER_ADDRESS, INCOMING_SERVER_PORT, INCOMING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_ADDRESS, OUTGOING_SERVER_PORT, OUTGOING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_REQUIRES_AUTHENTICATION, PROVIDER_NAME, SERVER_TYPE) VALUES ('poczta.o2.pl', 993, true, 'poczta.o2.pl', 465, true, true, 'O2_PL', 'IMAP');
INSERT INTO EMAIL_PROVIDER(INCOMING_SERVER_ADDRESS, INCOMING_SERVER_PORT, INCOMING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_ADDRESS, OUTGOING_SERVER_PORT, OUTGOING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_REQUIRES_AUTHENTICATION, PROVIDER_NAME, SERVER_TYPE) VALUES ('poczta.interia.pl', 993, true, 'poczta.interia.pl', 465, true, true, 'INTERIA', 'IMAP');
INSERT INTO EMAIL_PROVIDER(INCOMING_SERVER_ADDRESS, INCOMING_SERVER_PORT, INCOMING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_ADDRESS, OUTGOING_SERVER_PORT, OUTGOING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_REQUIRES_AUTHENTICATION, PROVIDER_NAME, SERVER_TYPE) VALUES ('imap.seznam.cz', 993, true, 'smtp.seznam.cz', 465, true, true, 'SEZNAM_CZ', 'IMAP');
INSERT INTO EMAIL_PROVIDER(INCOMING_SERVER_ADDRESS, INCOMING_SERVER_PORT, INCOMING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_ADDRESS, OUTGOING_SERVER_PORT, OUTGOING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_REQUIRES_AUTHENTICATION, PROVIDER_NAME, SERVER_TYPE) VALUES ('imap.centrum.cz', 993, true, 'smtp.centrum.cz', 465, true, true, 'CENTRUM_CZ', 'IMAP');
INSERT INTO EMAIL_PROVIDER(INCOMING_SERVER_ADDRESS, INCOMING_SERVER_PORT, INCOMING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_ADDRESS, OUTGOING_SERVER_PORT, OUTGOING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_REQUIRES_AUTHENTICATION, PROVIDER_NAME, SERVER_TYPE) VALUES ('imap.atlas.cz', 993, true, 'smtp.atlas.cz', 465, true, true, 'ATLAS_CZ', 'IMAP');
INSERT INTO EMAIL_PROVIDER(INCOMING_SERVER_ADDRESS, INCOMING_SERVER_PORT, INCOMING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_ADDRESS, OUTGOING_SERVER_PORT, OUTGOING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_REQUIRES_AUTHENTICATION, PROVIDER_NAME, SERVER_TYPE) VALUES ('imap.gmx.net', 993, true, 'mail.gmx.net', 465, true, true, 'GMX_EMAIL', 'IMAP');
INSERT INTO EMAIL_PROVIDER(INCOMING_SERVER_ADDRESS, INCOMING_SERVER_PORT, INCOMING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_ADDRESS, OUTGOING_SERVER_PORT, OUTGOING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_REQUIRES_AUTHENTICATION, PROVIDER_NAME, SERVER_TYPE) VALUES ('imap.yandex.com', 993, true, 'smtp.yandex.com', 465, true, true, 'YANDEX_MAIL', 'IMAP');
INSERT INTO EMAIL_PROVIDER(INCOMING_SERVER_ADDRESS, INCOMING_SERVER_PORT, INCOMING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_ADDRESS, OUTGOING_SERVER_PORT, OUTGOING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_REQUIRES_AUTHENTICATION, PROVIDER_NAME, SERVER_TYPE) VALUES ('imap.inbox.com', 993, true, 'smtp.inbox.com', 465, true, true, 'INBOX_COM', 'IMAP');
INSERT INTO EMAIL_PROVIDER(INCOMING_SERVER_ADDRESS, INCOMING_SERVER_PORT, INCOMING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_ADDRESS, OUTGOING_SERVER_PORT, OUTGOING_SERVER_REQUIRES_SSL, OUTGOING_SERVER_REQUIRES_AUTHENTICATION, PROVIDER_NAME, SERVER_TYPE) VALUES ('imap.mail.com', 993, true, 'smtp.mail.com', 465, true, true, 'MAIL.COM', 'IMAP');