/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kappadev.medplus.ui.profile;

import com.kappadev.medplus.data.profile.Profile;
import com.kappadev.medplus.data.profile.ProfileService;
import com.kappadev.medplus.ui.custom.MessagePopUp;
import com.kappadev.medplus.ui.settings.SettingsPanel;
import com.kappadev.medplus.utils.StringUtils;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author tburzynski
 */
@Component
public class AddOrUpdateProfilePanel extends javax.swing.JFrame {

    @Autowired
    private SettingsPanel settingsPanel;
    @Autowired
    private ProfileService profileService;
    @Autowired
    private SelectProfilePopUp selectProfilePopUp;

    private Profile profile = null;
    private MessagePopUp messagePopUp = new MessagePopUp();

    public void initAddOrUpdateProfilePanel() {
        initComponents();
        passwordTxtFld.setEnabled(true);
        this.profile = new Profile();
    }

    public void initAddOrUpdateProfilePanel(Profile profile) {
        this.profile = profile;
        initComponents();
        userNameTxtFLd.setText(profile.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        userNameTxtFLd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passwordTxtFld = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        changePasswordCheckBox = new javax.swing.JCheckBox();
        emailTxtFld = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        infoLbl = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Med Plus v0.4");

        jLabel2.setText("Nazwa użytkownika");

        jLabel3.setText("Hasło");

        passwordTxtFld.setEnabled(false);

        saveBtn.setText("Zapisz");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Anuluj");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        changePasswordCheckBox.setText("Zmiana hasła");
        changePasswordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordCheckBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("e-mail");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordTxtFld)
                    .addComponent(userNameTxtFLd)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(changePasswordCheckBox)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(emailTxtFld))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userNameTxtFLd, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(emailTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changePasswordCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(cancelBtn))
                .addContainerGap())
        );

        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout infoLblLayout = new javax.swing.GroupLayout(infoLbl);
        infoLbl.setLayout(infoLblLayout);
        infoLblLayout.setHorizontalGroup(
            infoLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLblLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(323, Short.MAX_VALUE))
        );
        infoLblLayout.setVerticalGroup(
            infoLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLblLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(infoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        if (validateUserNameField() && validatePasswordField() && validateEmailField()) {
            profile.setName(userNameTxtFLd.getText());
            profile.setPassword(StringUtils.getPasswordHash(passwordTxtFld.getText()));
            profile.setEmail(emailTxtFld.getText());
            profileService.saveProfile(profile);

            messagePopUp.setText("Dodano nowego użytkownika");
            messagePopUp.setVisible(true);
            this.dispose();
            selectProfilePopUp.setVisible(true);
            selectProfilePopUp.refreshUserComboBox();
        } else {

        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private boolean validateUserNameField() {
        if (userNameTxtFLd.getText().length() > 2) {
            return true;
        } else {
            messagePopUp.setText("Nazwa użytkownika musi zawierać co najmniej 3 znaki");
            messagePopUp.setVisible(true);
            return false;
        }
    }

    private boolean validatePasswordField() {
        if (passwordTxtFld.getText().length() > 6) {
            return true;
        } else {
            messagePopUp.setText("Hasło musi być dłuższe niż 6 znaków");
            messagePopUp.setVisible(true);
            return false;
        }
    }

    private boolean validateEmailField() {
        if (emailTxtFld.getText().length() > 6) {
            try {
                InternetAddress emailAddr = new InternetAddress(emailTxtFld.getText());
                emailAddr.validate();
                return true;
            } catch (AddressException ex) {
                Logger.getLogger(AddOrUpdateProfilePanel.class.getName()).log(Level.SEVERE, null, ex);
                messagePopUp.setText(ex.getLocalizedMessage());
                messagePopUp.setVisible(true);
                return false;
            }
        } else if (emailTxtFld.getText().length() == 0) {
            return true;
        } else {
            messagePopUp.setText("adres e-mail jest za krótki");
            messagePopUp.setVisible(true);
            return false;
        }

    }

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
        selectProfilePopUp.setVisible(true);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void changePasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordCheckBoxActionPerformed
        if (changePasswordCheckBox.isSelected()) {
            passwordTxtFld.setEnabled(true);
        } else {
            passwordTxtFld.setEnabled(false);
        }
    }//GEN-LAST:event_changePasswordCheckBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JCheckBox changePasswordCheckBox;
    private javax.swing.JTextField emailTxtFld;
    private javax.swing.JPanel infoLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField passwordTxtFld;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField userNameTxtFLd;
    // End of variables declaration//GEN-END:variables
}
