/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kappadev.medplus.ui.settings.accounts.email;

import com.kappadev.medplus.data.emailProvider.EmailProvider;
import com.kappadev.medplus.data.emailProvider.EmailProviderNameEnum;
import com.kappadev.medplus.data.emailProvider.EmailProviderService;
import com.kappadev.medplus.data.emailProvider.IncomingMailServerTypeEnum;
import com.kappadev.medplus.ui.settings.accounts.AccountsPanel;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author tburzynski
 */
@Component
public class EmailSettingPopUp extends javax.swing.JFrame {

    private static final Logger LOG = LoggerFactory.getLogger(EmailSettingPopUp.class);

    @Autowired
    private EmailProviderService emailProviderService;
    @Autowired
    private AccountsPanel accountsPanel;

    private List<EmailProvider> emailProviders;

    /**
     * Creates new form EmailSettingPopUp
     */
    public EmailSettingPopUp() {
        initComponents();
    }

    public void initEmailSettingPopUp() {
        initComponents();
        DefaultComboBoxModel<EmailProvider> emailProvidersComboBoxModel = new DefaultComboBoxModel<>();
        emailProviders = emailProviderService.getAllEmailProviders();
        emailProvidersComboBox.removeAllItems();
        for (EmailProvider emailProvider : emailProviders) {
            emailProvidersComboBoxModel.addElement(emailProvider);
        }
        emailProvidersComboBox.setModel(emailProvidersComboBoxModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        loginTxtFld = new javax.swing.JTextField();
        emailProvidersComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passwordTextFld = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        imapRadioBtn = new javax.swing.JRadioButton();
        pop3RadioBtn = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        incomingTxtFld = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        incomingPortTxtFld = new javax.swing.JTextField();
        incomingSSLcheckBox = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        smtpTxtFld = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        smtpPortTxtFld = new javax.swing.JTextField();
        smtpSSLcheckBox = new javax.swing.JCheckBox();
        smtpAuthorizationCheckBox = new javax.swing.JCheckBox();
        sameOutAsInCheckBox = new javax.swing.JCheckBox();
        mailNotificationsSwitcherCheckBox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 480));

        jPanel2.setMaximumSize(new java.awt.Dimension(200, 47));
        jPanel2.setMinimumSize(new java.awt.Dimension(200, 47));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 47));

        saveBtn.setText("Zapisz");
        saveBtn.setMaximumSize(new java.awt.Dimension(94, 25));
        saveBtn.setMinimumSize(new java.awt.Dimension(94, 25));
        saveBtn.setPreferredSize(new java.awt.Dimension(94, 25));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Anuluj");
        cancelBtn.setMaximumSize(new java.awt.Dimension(94, 25));
        cancelBtn.setMinimumSize(new java.awt.Dimension(94, 25));
        cancelBtn.setPreferredSize(new java.awt.Dimension(94, 25));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setText("Login");

        loginTxtFld.setText("wprowadz login");
        loginTxtFld.setPreferredSize(new java.awt.Dimension(70, 24));

        emailProvidersComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailProvidersComboBoxActionPerformed(evt);
            }
        });
        emailProvidersComboBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                emailProvidersComboBoxPropertyChange(evt);
            }
        });

        jLabel1.setText("usługodawca");

        jLabel4.setText("Hasło");

        passwordTextFld.setText("podaj hasło");
        passwordTextFld.setPreferredSize(new java.awt.Dimension(70, 24));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailProvidersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(loginTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(passwordTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loginTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailProvidersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel8.setText("Poczta przychodząca");

        jLabel5.setText("Typ serwera");

        buttonGroup1.add(imapRadioBtn);
        imapRadioBtn.setText("IMAP");
        imapRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imapRadioBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(pop3RadioBtn);
        pop3RadioBtn.setText("POP3");
        pop3RadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pop3RadioBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Adres serwera");

        incomingTxtFld.setPreferredSize(new java.awt.Dimension(70, 24));

        jLabel7.setText("Numer portu");

        incomingPortTxtFld.setPreferredSize(new java.awt.Dimension(70, 24));

        incomingSSLcheckBox.setText(" SSL");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(incomingTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(incomingPortTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(imapRadioBtn)
                        .addGap(18, 18, 18)
                        .addComponent(pop3RadioBtn))
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(incomingSSLcheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imapRadioBtn)
                    .addComponent(pop3RadioBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addComponent(incomingTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(incomingPortTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(incomingSSLcheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setText("Poczta wychodząca");

        jLabel11.setText("Adres serwera");

        smtpTxtFld.setText("server smtp");
        smtpTxtFld.setPreferredSize(new java.awt.Dimension(70, 24));

        jLabel12.setText("Numer portu");

        smtpPortTxtFld.setPreferredSize(new java.awt.Dimension(70, 24));

        smtpSSLcheckBox.setText(" SSL");

        smtpAuthorizationCheckBox.setText(" wymaga autoryzacji");

        sameOutAsInCheckBox.setText(" użyj ustawień poczty przychodzącej");
        sameOutAsInCheckBox.setToolTipText("");
        sameOutAsInCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sameOutAsInCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(smtpAuthorizationCheckBox)
                    .addComponent(smtpTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(smtpSSLcheckBox)
                    .addComponent(smtpPortTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(sameOutAsInCheckBox)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(10, 10, 10)
                .addComponent(smtpTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(smtpPortTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(smtpSSLcheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(smtpAuthorizationCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sameOutAsInCheckBox)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        mailNotificationsSwitcherCheckBox.setText(" włącz powiadomienia mailowe");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(208, 208, 208)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mailNotificationsSwitcherCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(mailNotificationsSwitcherCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setText("Med Plus v0.4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        goToAccountsPanel();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void imapRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imapRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imapRadioBtnActionPerformed

    private void pop3RadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pop3RadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pop3RadioBtnActionPerformed

    private void sameOutAsInCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sameOutAsInCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sameOutAsInCheckBoxActionPerformed

    private void emailProvidersComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailProvidersComboBoxActionPerformed
        if (emailProvidersComboBox.getModel().getSize() != 0) {
            EmailProvider selectedItem = (EmailProvider) emailProvidersComboBox.getModel().getSelectedItem();
            if (selectedItem != null) {
                if (EmailProviderNameEnum.valueOf(selectedItem.getName()) == EmailProviderNameEnum.OTHER) {
                    enableEmailProviderComponents(true);
                } else {
                    enableEmailProviderComponents(false);
                    EmailProvider selectedValue = (EmailProvider) emailProvidersComboBox.getModel().getSelectedItem();
                    EmailProvider emailProvider = null;
                    if (imapRadioBtn.isSelected()) {
                        emailProvider = emailProviderService.getEmailProviderByServerTypeAndName(IncomingMailServerTypeEnum.IMAP, EmailProviderNameEnum.valueOf(selectedValue.getName()));
                    }
                    if (emailProvider != null) {
                        smtpTxtFld.setText(emailProvider.getSmtpAddress());
                        smtpPortTxtFld.setText(String.valueOf(emailProvider.getSmtpPort()));
                        incomingPortTxtFld.setText(String.valueOf(emailProvider.getIncomingServerPort()));
                        incomingTxtFld.setText(emailProvider.getIncomingServerAddress());
                    } else {
                        LOG.error("ERROR", "email provider entity is null");
                    }
                }
            }
        } else {
            LOG.error("ERROR", "emailProviderComboBox model is empty");
        }
    }//GEN-LAST:event_emailProvidersComboBoxActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        goToAccountsPanel();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void emailProvidersComboBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_emailProvidersComboBoxPropertyChange


    }//GEN-LAST:event_emailProvidersComboBoxPropertyChange

    private void enableEmailProviderComponents(boolean enable) {
        smtpTxtFld.setEnabled(enable);
        smtpPortTxtFld.setEnabled(enable);
        incomingPortTxtFld.setEnabled(false);
        incomingTxtFld.setEnabled(enable);
    }

    private void goToAccountsPanel() {
        this.dispose();
        accountsPanel.initAccountsPanel();
        accountsPanel.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox<EmailProvider> emailProvidersComboBox;
    private javax.swing.JRadioButton imapRadioBtn;
    private javax.swing.JTextField incomingPortTxtFld;
    private javax.swing.JCheckBox incomingSSLcheckBox;
    private javax.swing.JTextField incomingTxtFld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField loginTxtFld;
    private javax.swing.JCheckBox mailNotificationsSwitcherCheckBox;
    private javax.swing.JTextField passwordTextFld;
    private javax.swing.JRadioButton pop3RadioBtn;
    private javax.swing.JCheckBox sameOutAsInCheckBox;
    private javax.swing.JButton saveBtn;
    private javax.swing.JCheckBox smtpAuthorizationCheckBox;
    private javax.swing.JTextField smtpPortTxtFld;
    private javax.swing.JCheckBox smtpSSLcheckBox;
    private javax.swing.JTextField smtpTxtFld;
    // End of variables declaration//GEN-END:variables
}
