/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.kappadev.medplus.ui.tools;

import java.io.File;
import com.kappadev.medplus.ui.tools.dataMigration.DataMigrationWindow;
import com.kappadev.medplus.ui.main.MainMenuPanel;
import com.kappadev.medplus.data.DiskDrive.DiskDrive;
import com.kappadev.medplus.data.migration.DataMigrationConstants;
import com.kappadev.medplus.utils.CopyUtil;


/**
 *
 * @author chlast
 */
public class ToolsPanel extends javax.swing.JFrame {

    /**
     * Creates new form Tools
     */
    public ToolsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        importBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        exportBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fileNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        importBtn.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        importBtn.setText("Importuj\n");
        importBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Med Plus v0.3");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 16)); // NOI18N
        jLabel2.setText("Narzędzia do migracji danych ");

        jLabel3.setText("import danych z zewnętrznego dysku\n");

        jLabel4.setText("eksport danych na zewnętrzny dysk");

        exportBtn.setText("Eksportuj");
        exportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Powrót");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        progressBar.setStringPainted(true);
        progressBar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                progressBarPropertyChange(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel5.setText("Postęp:");

        jLabel6.setText("Plik:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(importBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exportBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fileNameLabel)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fileNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importBtnActionPerformed
        DataMigrationWindow dmw = new DataMigrationWindow(DataMigrationConstants.DATA_MIGRATION_IMPORT);
        dmw.setVisible(rootPaneCheckingEnabled);
        DiskDrive dd = dmw.getSelectedDiskDrive();
        if(dd.getPath()!=null){
           File medRegistryDir = new File(dd.getPath()+File.separator+DataMigrationConstants.DATA_MIGRATION_FILES_FOLDER);
           if(medRegistryDir.exists()){
              File databaseFileInput = new File(dd.getPath()+File.separator+DataMigrationConstants.DATA_MIGRATION_DATABASE_FILE);
              File databaseTraceFileInput = new File(dd.getPath()+File.separator+DataMigrationConstants.DATA_MIGRATION_DATABASE_TRACE_FILE);
              File databaseFileOutput = new File(System.getProperty(DataMigrationConstants.USER_HOME_DIR)+File.separator+DataMigrationConstants.DATA_MIGRATION_DATABASE_FILE);
              File databaseTraceOutput = new File(System.getProperty(DataMigrationConstants.USER_HOME_DIR)+File.separator+DataMigrationConstants.DATA_MIGRATION_DATABASE_TRACE_FILE);
              CopyUtil databaseFiles = new CopyUtil(databaseFileInput, databaseFileOutput, progressBar);
              fileNameLabel.setText(DataMigrationConstants.DATA_MIGRATION_DATABASE_FILE);
              databaseFiles.execute();
              CopyUtil databaseTraceFiles = new CopyUtil(databaseTraceFileInput, databaseTraceOutput, progressBar); 
              fileNameLabel.setText(DataMigrationConstants.DATA_MIGRATION_DATABASE_TRACE_FILE);
              databaseTraceFiles.execute();
           }
        }
    }//GEN-LAST:event_importBtnActionPerformed
   
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        MainMenuPanel mp = new MainMenuPanel();
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void exportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportBtnActionPerformed
        DataMigrationWindow dmw = new DataMigrationWindow(DataMigrationConstants.DATA_MIGRATION_EXPORT);
        dmw.setVisible(rootPaneCheckingEnabled);
        DiskDrive dd = dmw.getSelectedDiskDrive();
        if(dd.getPath()!=null){     
              File databaseFileInput = new File(System.getProperty(DataMigrationConstants.USER_HOME_DIR)+File.separator+DataMigrationConstants.DATA_MIGRATION_DATABASE_FILE);
              File databaseTraceFileInput = new File(System.getProperty(DataMigrationConstants.USER_HOME_DIR)+File.separator+DataMigrationConstants.DATA_MIGRATION_DATABASE_TRACE_FILE);
              File databaseFileOutput =  new File(dd.getPath()+File.separator+DataMigrationConstants.DATA_MIGRATION_DATABASE_FILE);
              File databaseTraceOutput = new File(dd.getPath()+File.separator+DataMigrationConstants.DATA_MIGRATION_DATABASE_TRACE_FILE);
              CopyUtil databaseFiles = new CopyUtil(databaseFileInput, databaseFileOutput, progressBar);
              fileNameLabel.setText(DataMigrationConstants.DATA_MIGRATION_DATABASE_FILE);
              databaseFiles.execute();
              CopyUtil databaseTraceFiles = new CopyUtil(databaseTraceFileInput, databaseTraceOutput, progressBar);  
              fileNameLabel.setText(DataMigrationConstants.DATA_MIGRATION_DATABASE_TRACE_FILE);
              databaseTraceFiles.execute();
        }
    }//GEN-LAST:event_exportBtnActionPerformed

    private void progressBarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_progressBarPropertyChange
         
    }//GEN-LAST:event_progressBarPropertyChange

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton exportBtn;
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JButton importBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
